// Copyright (c) 2021 Gitpod GmbH. All rights reserved.
// Licensed under the GNU Affero General Public License (AGPL).
// See License-AGPL.txt in the project root for license information.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogServiceClient is the client API for LogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogServiceClient interface {
	// LogDownloadURL provides a URL from where the content of a workspace can be downloaded from
	LogDownloadURL(ctx context.Context, in *LogDownloadURLRequest, opts ...grpc.CallOption) (*LogDownloadURLResponse, error)
	// ListPrebuildLogs returns a list of taskIds for the specified workspace instance
	ListPrebuildLogs(ctx context.Context, in *ListPrebuildLogsRequest, opts ...grpc.CallOption) (*ListPrebuildLogsResponse, error)
}

type logServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogServiceClient(cc grpc.ClientConnInterface) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) LogDownloadURL(ctx context.Context, in *LogDownloadURLRequest, opts ...grpc.CallOption) (*LogDownloadURLResponse, error) {
	out := new(LogDownloadURLResponse)
	err := c.cc.Invoke(ctx, "/contentservice.LogService/LogDownloadURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) ListPrebuildLogs(ctx context.Context, in *ListPrebuildLogsRequest, opts ...grpc.CallOption) (*ListPrebuildLogsResponse, error) {
	out := new(ListPrebuildLogsResponse)
	err := c.cc.Invoke(ctx, "/contentservice.LogService/ListPrebuildLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServiceServer is the server API for LogService service.
// All implementations must embed UnimplementedLogServiceServer
// for forward compatibility
type LogServiceServer interface {
	// LogDownloadURL provides a URL from where the content of a workspace can be downloaded from
	LogDownloadURL(context.Context, *LogDownloadURLRequest) (*LogDownloadURLResponse, error)
	// ListPrebuildLogs returns a list of taskIds for the specified workspace instance
	ListPrebuildLogs(context.Context, *ListPrebuildLogsRequest) (*ListPrebuildLogsResponse, error)
	mustEmbedUnimplementedLogServiceServer()
}

// UnimplementedLogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLogServiceServer struct {
}

func (UnimplementedLogServiceServer) LogDownloadURL(context.Context, *LogDownloadURLRequest) (*LogDownloadURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogDownloadURL not implemented")
}
func (UnimplementedLogServiceServer) ListPrebuildLogs(context.Context, *ListPrebuildLogsRequest) (*ListPrebuildLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPrebuildLogs not implemented")
}
func (UnimplementedLogServiceServer) mustEmbedUnimplementedLogServiceServer() {}

// UnsafeLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServiceServer will
// result in compilation errors.
type UnsafeLogServiceServer interface {
	mustEmbedUnimplementedLogServiceServer()
}

func RegisterLogServiceServer(s grpc.ServiceRegistrar, srv LogServiceServer) {
	s.RegisterService(&LogService_ServiceDesc, srv)
}

func _LogService_LogDownloadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogDownloadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).LogDownloadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contentservice.LogService/LogDownloadURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).LogDownloadURL(ctx, req.(*LogDownloadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_ListPrebuildLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPrebuildLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).ListPrebuildLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contentservice.LogService/ListPrebuildLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).ListPrebuildLogs(ctx, req.(*ListPrebuildLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogService_ServiceDesc is the grpc.ServiceDesc for LogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contentservice.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogDownloadURL",
			Handler:    _LogService_LogDownloadURL_Handler,
		},
		{
			MethodName: "ListPrebuildLogs",
			Handler:    _LogService_ListPrebuildLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log.proto",
}
