# Copyright (c) 2021 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ $comp := .Values.components.proxy -}}
{{ $certManager := (index .Values "cert-manager") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: proxy-config-certificates
spec:
  secretName: proxy-config-certificates
  commonName: {{ .Values.hostname | quote }}
  dnsNames:
    - {{ .Values.hostname | quote }}
    - "*.{{ .Values.hostname }}"
    - "*.ws{{- if .Values.installation.shortname -}}-{{ .Values.installation.shortname }}{{- end -}}.{{ .Values.hostname }}"
  issuerRef:
    name: {{ $comp.certManager.issuerName | default $certManager.ca.issuerName }}
    kind: ClusterIssuer
    group: cert-manager.io
